export const courses = [
    {
        title: 'Introduction to Computer Science',
        description: 'An introduction to the intellectual enterprises of computer science and the art of programming.',
        category: 'Computer Science Basics',
        school: 'Harvard',
        duration: '10 weeks',
        effort: '10-20 hours/week',
        frequency: 'self-paced',
        rating: -1,
        image: 'https://prod-discovery.edx-cdn.org/media/course/image/da1b2400-322b-459b-97b0-0c557f05d017-a3d1899c3344.png',
        link: 'https://www.edx.org/course/cs50s-introduction-computer-science-harvardx-cs50x',
    },
    {
        title: 'Java Programming: Solving Problems with Software',
        description: 'Learn to code in Java and improve your programming and problem-solving skills.',
        category: 'Programming',
        school: 'Duke',
        duration: '4 weeks',
        effort: '4-8 hours/week',
        frequency: 'twice a month',
        rating: 4.6,
        image: 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/b6/2019201a9e11e5ace08b26adce8cb5/Java.png?auto=format%2Ccompress%2C%20enhance&dpr=2&w=600&h=216&fit=fill&q=50',
        link: 'https://www.coursera.org/learn/java-programming?irclickid=UD6RDmVfDxyNWWG1yP0cqV3pUkAQkCylQVvYWI0&irgwc=1&utm_medium=partners&utm_source=impact&utm_campaign=1459666&utm_content=b2c',
    },
    {
        title: 'Java Programming: Arrays, Lists, and Structured Data',
        description: '',
        category: 'Programming',
        school: 'Duke',
        duration: '4 weeks',
        effort: '4-8 hours/week',
        frequency: 'twice a month',
        image: 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/45/3b4810378111e5aec5ffdf45dcbb85/work-731198_1280.jpg?auto=format%2Ccompress%2C%20enhance&dpr=2&w=600&h=216&fit=fill&q=50',
        link: 'https://imp.i384100.net/15knRR',
    },
    {
        title: 'Object Oriented Programming in Java',
        description: '',
        category: 'Programming',
        school: 'UCSD',
        duration: '6 weeks',
        effort: '',
        frequency: '',
        image: 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/87/15cd50462711e5afab87f02cb13490/Course1.jpg?auto=format%2Ccompress%2C%20enhance&dpr=2&w=600&h=216&fit=fill&q=50',
        link: 'https://www.coursera.org/learn/object-oriented-java?irclickid=ybbXbhyvmxyNUtbz4oWQCVcdUkAx9uXdQVvYWI0&irgwc=1&utm_medium=partners&utm_source=impact&utm_campaign=1459666&utm_content=b2c',
    },
    {
        title: 'Data Structures and Performance',
        description: '',
        category: 'Programming',
        school: 'UCSD',
        duration: '6 weeks',
        effort: '',
        frequency: '',
        image: 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/0f/50a380462711e5897a1dde7aef8b48/Course2.jpg?auto=format%2Ccompress%2C%20enhance&dpr=2&w=600&h=216&fit=fill&q=50',
        link: 'https://www.coursera.org/learn/data-structures-optimizing-performance?irclickid=ybbXbhyvmxyNUtbz4oWQCVcdUkAx9uTZQVvYWI0&irgwc=1&utm_medium=partners&utm_source=impact&utm_campaign=1459666&utm_content=b2c',
    },
    {
        title: 'Java Programming: Principles of Software Design',
        description: '',
        category: 'Programming',
        school: 'Duke',
        duration: '4 weeks',
        effort: '',
        frequency: '',
        image: 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/67/19a170378111e5bb340fc2063e9b79/board-453758_1280.jpg?auto=format%2Ccompress%2C%20enhance&dpr=2&w=600&h=216&fit=fill&q=50',
        link: 'https://www.coursera.org/learn/java-programming-design-principles?irclickid=ybbXbhyvmxyNUtbz4oWQCVcdUkAx9r0hQVvYWI0&irgwc=1&utm_medium=partners&utm_source=impact&utm_campaign=1459666&utm_content=b2c',
    },
    {
        title: 'Java Programming: Build a Recommendation System',
        description: '',
        category: 'Programming',
        school: '',
        duration: '4 weeks',
        effort: '',
        frequency: '',
        image: 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/18/a302e04daf11e59c90d5d1f3c33638/tree-200795_1280.jpg?auto=format%2Ccompress%2C%20enhance&dpr=2&w=600&h=216&fit=fill&q=50',
        link: 'https://www.coursera.org/learn/java-programming-recommender?irclickid=ybbXbhyvmxyNUtbz4oWQCVcdUkAx9r15QVvYWI0&irgwc=1&utm_medium=partners&utm_source=impact&utm_campaign=1459666&utm_content=b2c',
    },
    {
        title: 'Programming Languages, Part A',
        description: 'This course is an introduction to the basic concepts of programming languages, with a strong emphasis on functional programming.',
        category: 'Programming',
        school: 'UW',
        duration: '5 weeks',
        effort: '',
        frequency: '',
        image: 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/9b/39a3f0373111e69ce719fe5f0d2d9d/Capture.png?auto=format%2Ccompress%2C%20enhance&dpr=2&w=600&h=216&fit=fill&q=50',
        link: 'https://www.coursera.org/learn/programming-languages',
    },
    {
        title: 'Programming Languages, Part B',
        description: 'This course is an introduction to the basic concepts of programming languages, with a strong emphasis on functional programming.',
        category: '',
        school: 'UW',
        duration: '3 weeks',
        effort: '',
        frequency: '',
        image: 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/64/9607d0528911e6af3d1f5b788773cd/partb_logo_square.png?auto=format%2Ccompress%2C%20enhance&dpr=2&w=600&h=216&fit=fill&q=50',
        link: 'https://www.coursera.org/learn/programming-languages-part-b',
    },
    {
        title: 'Programming Languages, Part C',
        description: 'This course is an introduction to the basic concepts of programming languages, with a strong emphasis on functional programming.',
        category: '',
        school: 'UW',
        duration: '3 weeks',
        effort: '',
        frequency: '',
        image: 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/f5/51c300658911e6815cedc942c833a6/partc_logo_square.png?auto=format%2Ccompress%2C%20enhance&dpr=2&w=600&h=216&fit=fill&q=50',
        link: 'https://www.coursera.org/learn/programming-languages-part-c',
    },
    {
        title: 'Calculus 1A: Differentiation',
        description: '',
        category: 'Mathematics',
        school: 'MIT',
        duration: '13 weeks',
        effort: '',
        frequency: '',
        image: 'https://prod-discovery.edx-cdn.org/media/course/image/64aa9258-a9da-4fcc-a0e6-fc803bd2fe56-aeb040d95114.jpg',
        link: 'https://www.edx.org/course/calculus-1a-differentiation',
    },
    {
        title: 'Calculus 1B: Integration',
        description: '',
        category: 'Mathematics',
        school: 'MIT',
        duration: '15 weeks',
        effort: '',
        frequency: '',
        image: 'https://prod-discovery.edx-cdn.org/media/course/image/9359cd1d-8478-4784-888b-dea198ce4722-3219c4264f1d.jpg',
        link: 'https://www.edx.org/course/calculus-1b-integration',
    },
    {
        title: 'Calculus 1C: Coordinate Systems & Infinite Series',
        description: '',
        category: 'Mathematics',
        school: 'MIT',
        duration: '13 weeks',
        effort: '',
        frequency: '',
        image: 'https://prod-discovery.edx-cdn.org/media/course/image/fd92782d-f46f-401b-97d3-fc7bb0266c6f-d17d0dbc93e2.jpg',
        link: 'https://www.edx.org/course/calculus-1c-coordinate-systems-infinite-series',
    },
    {
        title: 'Linear Algebra - Foundations to Frontiers',
        description: '',
        category: '',
        school: 'UT Austin',
        duration: '15 weeks',
        effort: '',
        frequency: '',
        image: 'https://prod-discovery.edx-cdn.org/media/course/image/16e7e19f-9036-4916-a1c8-2b799b502212-8f52e8838f53.jpg',
        link: 'https://www.edx.org/course/linear-algebra-foundations-to-frontiers',
    },
  ];